# Types: --------------------------------------------------------------------------------------------------
type Curso {
    titulo: String
}

type Tecnologia {
    tecnologia: String
}

# Queries: ------------------------------------------------------------------------------------------------
type Query {
    obtenerCursos: [Curso],
    obtenerTecnologias: [Tecnologia]
}